-- ============================================================
-- Legacy v0.1 fixture (sanitized) — 用于 LegacyH2UpgradeTest
-- ============================================================
-- 目的：模拟一个已部署的 v0.1 KylinOps H2 数据库（8 张 legacy 表 +
--      少量脱敏种子数据），由 LegacyH2UpgradeTest 通过 H2 RUNSCRIPT 加载，
--      触发 Flyway baseline-on-migrate=true / baseline-version=1，
--      验证 V2 增量迁移不会破坏 v0.1 数据。
--
-- 脱敏要求（来自 phase1-runtime-database-plan §Task 2）：
--   * 不写入真实账号、口令、IP、文件路径
--   * 用户输入、审计消息等仅写语义占位符文本
--   * 时间戳固定到 2026-05-01（升级测试可复现）
--   * UUID 为确定值，方便断言
-- ============================================================

-- ---------- 8 张 v0.1 legacy 表的 schema（与 V1__legacy_schema.sql 完全一致） ----------
CREATE TABLE kylin_session (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    session_id  VARCHAR(36)  NOT NULL UNIQUE,
    title       VARCHAR(256),
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
);

CREATE TABLE kylin_message (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    message_id  VARCHAR(36)  NOT NULL UNIQUE,
    session_id  BIGINT       NOT NULL,
    role        VARCHAR(16)  NOT NULL,
    content     TEXT         NOT NULL,
    intent_type VARCHAR(32),
    audit_id    VARCHAR(36),
    CONSTRAINT fk_message_session
        FOREIGN KEY (session_id) REFERENCES kylin_session(id)
);

CREATE INDEX idx_message_session ON kylin_message(session_id);
CREATE INDEX idx_message_audit_id ON kylin_message(audit_id);

CREATE TABLE kylin_audit_log (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL,
    audit_id               VARCHAR(36)  NOT NULL UNIQUE,
    session_id             VARCHAR(36),
    user_input             TEXT,
    intent_type            VARCHAR(32),
    tool_name              VARCHAR(64),
    risk_level             VARCHAR(8),
    risk_decision          VARCHAR(12),
    status                 VARCHAR(20)  NOT NULL,
    message                TEXT,
    duration_ms            BIGINT,
    matched_rules          TEXT,
    action_plan            TEXT,
    confirmation_required  BOOLEAN      NOT NULL DEFAULT FALSE,
    confirmation_status    VARCHAR(20),
    execution_result       TEXT,
    final_answer           TEXT,
    warning                TEXT
);

CREATE INDEX idx_audit_session_id ON kylin_audit_log(session_id);
CREATE INDEX idx_audit_status     ON kylin_audit_log(status);

CREATE TABLE kylin_tool_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    tool_name       VARCHAR(64)  NOT NULL UNIQUE,
    description     VARCHAR(512) NOT NULL,
    input_schema    TEXT,
    output_schema   TEXT,
    risk_level      VARCHAR(8)   NOT NULL,
    permission_type VARCHAR(12)  NOT NULL,
    tool_status     VARCHAR(12)  NOT NULL DEFAULT 'ENABLED',
    timeout_ms      BIGINT       NOT NULL DEFAULT 3000,
    audit_required  BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE kylin_tool_call_record (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL,
    tool_call_id        VARCHAR(36)  NOT NULL UNIQUE,
    message_id          BIGINT,
    tool_name           VARCHAR(64)  NOT NULL,
    input               TEXT,
    output              TEXT,
    status              VARCHAR(16)  NOT NULL,
    duration_ms         BIGINT,
    error_message       TEXT,
    audit_id            VARCHAR(36),
    CONSTRAINT fk_tool_call_message
        FOREIGN KEY (message_id) REFERENCES kylin_message(id)
);

CREATE INDEX idx_tool_call_message_id ON kylin_tool_call_record(message_id);
CREATE INDEX idx_tool_call_audit_id   ON kylin_tool_call_record(audit_id);

CREATE TABLE kylin_risk_check_record (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL,
    risk_check_id          VARCHAR(36)  NOT NULL UNIQUE,
    target_type            VARCHAR(20),
    target_content         TEXT,
    tool_call_record_id    BIGINT,
    risk_level             VARCHAR(8)   NOT NULL,
    risk_decision          VARCHAR(12)  NOT NULL,
    matched_rules          TEXT,
    reason                 TEXT         NOT NULL,
    safe_suggestion        TEXT,
    audit_id               VARCHAR(36),
    checked_at             TIMESTAMP    NOT NULL,
    CONSTRAINT fk_risk_check_tool_call
        FOREIGN KEY (tool_call_record_id) REFERENCES kylin_tool_call_record(id)
);

CREATE INDEX idx_risk_check_tool_call_id ON kylin_risk_check_record(tool_call_record_id);
CREATE INDEX idx_risk_check_audit_id     ON kylin_risk_check_record(audit_id);

CREATE TABLE kylin_pending_action (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP NOT NULL,
    action_id        VARCHAR(36)  NOT NULL UNIQUE,
    audit_id         VARCHAR(64)  NOT NULL,
    session_id       VARCHAR(64),
    action_type      VARCHAR(64)  NOT NULL,
    tool_name        VARCHAR(128),
    params_json      TEXT,
    risk_level       VARCHAR(8)   NOT NULL,
    status           VARCHAR(16)  NOT NULL,
    expires_at       TIMESTAMP    NOT NULL,
    execution_result TEXT
);

CREATE INDEX idx_pending_action_audit_id   ON kylin_pending_action(audit_id);
CREATE INDEX idx_pending_action_session_id ON kylin_pending_action(session_id);
CREATE INDEX idx_pending_action_status     ON kylin_pending_action(status);

CREATE TABLE kylin_report (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    report_id      VARCHAR(36)  NOT NULL UNIQUE,
    report_type    VARCHAR(32)  NOT NULL,
    title          VARCHAR(256) NOT NULL,
    session_id     VARCHAR(36),
    audit_id       VARCHAR(36)  NOT NULL,
    risk_level     VARCHAR(8),
    body_markdown  CLOB         NOT NULL
);

CREATE INDEX idx_report_audit_id          ON kylin_report(audit_id);
CREATE INDEX idx_report_session_created   ON kylin_report(session_id, created_at);

-- ---------- 脱敏种子数据 ----------
-- 1 个 session + 1 条 user message + 1 条 assistant message（确认链路完整性）
INSERT INTO kylin_session (id, created_at, updated_at, session_id, title, status)
VALUES (1, TIMESTAMP '2026-05-01 09:00:00', TIMESTAMP '2026-05-01 09:00:00',
        'sess-fixture-0001', 'fixture session', 'ACTIVE');

INSERT INTO kylin_message (id, created_at, updated_at, message_id, session_id, role, content, intent_type, audit_id)
VALUES (1, TIMESTAMP '2026-05-01 09:00:01', TIMESTAMP '2026-05-01 09:00:01',
        'msg-fixture-0001-user', 1, 'USER',
        '[fixture] sanitized user input placeholder', 'SYSTEM_HEALTH_CHECK',
        'aud-fixture-0001');

INSERT INTO kylin_message (id, created_at, updated_at, message_id, session_id, role, content, intent_type, audit_id)
VALUES (2, TIMESTAMP '2026-05-01 09:00:02', TIMESTAMP '2026-05-01 09:00:02',
        'msg-fixture-0001-asst', 1, 'ASSISTANT',
        '[fixture] sanitized assistant reply placeholder', 'SYSTEM_HEALTH_CHECK',
        'aud-fixture-0001');

-- 1 条 kylin_audit_log（必须保留 — V2 升级后断言存在）
INSERT INTO kylin_audit_log (id, created_at, updated_at, audit_id, session_id, user_input,
                              intent_type, tool_name, risk_level, risk_decision, status,
                              message, confirmation_required)
VALUES (1, TIMESTAMP '2026-05-01 09:00:01', TIMESTAMP '2026-05-01 09:00:03',
        'aud-fixture-0001', 'sess-fixture-0001',
        '[fixture] sanitized user input placeholder',
        'SYSTEM_HEALTH_CHECK', 'system_info_tool', 'L0', 'ALLOW', 'SUCCESS',
        '[fixture] sanitized audit message placeholder', FALSE);

-- 1 条 kylin_report（必须保留 — V2 升级后断言存在）
INSERT INTO kylin_report (id, created_at, updated_at, report_id, report_type, title,
                          session_id, audit_id, risk_level, body_markdown)
VALUES (1, TIMESTAMP '2026-05-01 09:00:04', TIMESTAMP '2026-05-01 09:00:04',
        'rpt-fixture-0001', 'HEALTH', '[fixture] sanitized health report',
        'sess-fixture-0001', 'aud-fixture-0001', 'L0',
        '[fixture] sanitized markdown body placeholder');
