-- ============================================================
-- V1: Legacy Schema Baseline
-- ============================================================
-- 目标：精确还原当前 8 张 JPA 实体对应的 legacy 表结构，1:1 对齐：
--   * chat/Session.java           -> kylin_session
--   * chat/Message.java           -> kylin_message
--   * audit/AuditLog.java         -> kylin_audit_log
--   * tool/ToolDefinition.java    -> kylin_tool_definition
--   * tool/ToolCallRecord.java    -> kylin_tool_call_record
--   * security/RiskCheckRecord.java -> kylin_risk_check_record
--   * executor/PendingAction.java -> kylin_pending_action
--   * report/Report.java          -> kylin_report
--
-- 安全红线（CLAUDE.md）：
--   * 不引入 auth 字段（V2 任务）
--   * 不引入 execution-attempt 字段（V2 任务）
--   * 保持所有 unique 约束（含 kylin_pending_action.actionId 唯一）
--
-- SQL 兼容性：
--   * bigint generated by default as identity（H2 PostgreSQL 模式 + 真实 PostgreSQL 12+ 均支持）
--   * varchar / text / timestamp -- 公共子集
--   * 不使用 H2 / PostgreSQL 私有类型
-- ============================================================

-- ---------- kylin_session ----------
CREATE TABLE kylin_session (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    session_id  VARCHAR(36)  NOT NULL UNIQUE,
    title       VARCHAR(256),
    status      VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE'
);

-- ---------- kylin_message ----------
CREATE TABLE kylin_message (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP NOT NULL,
    message_id  VARCHAR(36)  NOT NULL UNIQUE,
    session_id  BIGINT       NOT NULL,
    role        VARCHAR(16)  NOT NULL,
    content     TEXT         NOT NULL,
    intent_type VARCHAR(32),
    audit_id    VARCHAR(36),
    CONSTRAINT fk_message_session
        FOREIGN KEY (session_id) REFERENCES kylin_session(id)
);

CREATE INDEX idx_message_session ON kylin_message(session_id);
CREATE INDEX idx_message_audit_id ON kylin_message(audit_id);

-- ---------- kylin_audit_log ----------
CREATE TABLE kylin_audit_log (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL,
    audit_id               VARCHAR(36)  NOT NULL UNIQUE,
    session_id             VARCHAR(36),
    user_input             TEXT,
    intent_type            VARCHAR(32),
    tool_name              VARCHAR(64),
    risk_level             VARCHAR(8),
    risk_decision          VARCHAR(12),
    status                 VARCHAR(20)  NOT NULL,
    message                TEXT,
    duration_ms            BIGINT,
    matched_rules          TEXT,
    action_plan            TEXT,
    confirmation_required  BOOLEAN      NOT NULL DEFAULT FALSE,
    confirmation_status    VARCHAR(20),
    execution_result       TEXT,
    final_answer           TEXT,
    warning                TEXT
);

CREATE INDEX idx_audit_session_id ON kylin_audit_log(session_id);
CREATE INDEX idx_audit_status     ON kylin_audit_log(status);

-- ---------- kylin_tool_definition ----------
CREATE TABLE kylin_tool_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP NOT NULL,
    tool_name       VARCHAR(64)  NOT NULL UNIQUE,
    description     VARCHAR(512) NOT NULL,
    input_schema    TEXT,
    output_schema   TEXT,
    risk_level      VARCHAR(8)   NOT NULL,
    permission_type VARCHAR(12)  NOT NULL,
    tool_status     VARCHAR(12)  NOT NULL DEFAULT 'ENABLED',
    timeout_ms      BIGINT       NOT NULL DEFAULT 3000,
    audit_required  BOOLEAN      NOT NULL DEFAULT TRUE
);

-- ---------- kylin_tool_call_record ----------
CREATE TABLE kylin_tool_call_record (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP NOT NULL,
    tool_call_id        VARCHAR(36)  NOT NULL UNIQUE,
    message_id          BIGINT,
    tool_name           VARCHAR(64)  NOT NULL,
    input               TEXT,
    output              TEXT,
    status              VARCHAR(16)  NOT NULL,
    duration_ms         BIGINT,
    error_message       TEXT,
    audit_id            VARCHAR(36),
    CONSTRAINT fk_tool_call_message
        FOREIGN KEY (message_id) REFERENCES kylin_message(id)
);

CREATE INDEX idx_tool_call_message_id ON kylin_tool_call_record(message_id);
CREATE INDEX idx_tool_call_audit_id   ON kylin_tool_call_record(audit_id);

-- ---------- kylin_risk_check_record ----------
CREATE TABLE kylin_risk_check_record (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at             TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP NOT NULL,
    risk_check_id          VARCHAR(36)  NOT NULL UNIQUE,
    target_type            VARCHAR(20),
    target_content         TEXT,
    tool_call_record_id    BIGINT,
    risk_level             VARCHAR(8)   NOT NULL,
    risk_decision          VARCHAR(12)  NOT NULL,
    matched_rules          TEXT,
    reason                 TEXT         NOT NULL,
    safe_suggestion        TEXT,
    audit_id               VARCHAR(36),
    checked_at             TIMESTAMP    NOT NULL,
    CONSTRAINT fk_risk_check_tool_call
        FOREIGN KEY (tool_call_record_id) REFERENCES kylin_tool_call_record(id)
);

CREATE INDEX idx_risk_check_tool_call_id ON kylin_risk_check_record(tool_call_record_id);
CREATE INDEX idx_risk_check_audit_id     ON kylin_risk_check_record(audit_id);

-- ---------- kylin_pending_action ----------
CREATE TABLE kylin_pending_action (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP NOT NULL,
    updated_at       TIMESTAMP NOT NULL,
    action_id        VARCHAR(36)  NOT NULL UNIQUE,
    audit_id         VARCHAR(64)  NOT NULL,
    session_id       VARCHAR(64),
    action_type      VARCHAR(64)  NOT NULL,
    tool_name        VARCHAR(128),
    params_json      TEXT,
    risk_level       VARCHAR(8)   NOT NULL,
    status           VARCHAR(16)  NOT NULL,
    expires_at       TIMESTAMP    NOT NULL,
    execution_result TEXT
);

CREATE INDEX idx_pending_action_audit_id   ON kylin_pending_action(audit_id);
CREATE INDEX idx_pending_action_session_id ON kylin_pending_action(session_id);
CREATE INDEX idx_pending_action_status     ON kylin_pending_action(status);

-- ---------- kylin_report ----------
CREATE TABLE kylin_report (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP    NOT NULL,
    report_id      VARCHAR(36)  NOT NULL UNIQUE,
    report_type    VARCHAR(32)  NOT NULL,
    title          VARCHAR(256) NOT NULL,
    session_id     VARCHAR(36),
    audit_id       VARCHAR(36)  NOT NULL,
    risk_level     VARCHAR(8),
    body_markdown  CLOB         NOT NULL
);

CREATE INDEX idx_report_audit_id          ON kylin_report(audit_id);
CREATE INDEX idx_report_session_created   ON kylin_report(session_id, created_at);