-- ============================================================
-- V2: Execution Audit Schema (Phase 1 Task 2)
-- ============================================================
-- 目标：在 V1 基线之上增量引入「执行原子审计」所需的列与新表。
-- 严格遵守 CLAUDE.md / phase1-runtime-database-plan §Task 2：
--   * 仅增量：不删列、不改名、不破坏 V1 数据
--   * 不引用 V1 旧表的外键（V2 新表之间可互引）
--   * 不创建 v0.1 / Phase 1 Task 4 还未设计的实体对应列
--   * SQL 子集：bigint generated by default as identity / varchar / text / timestamp
-- ============================================================

-- ---------- kylin_pending_action：增量 auth ownership 列 ----------
-- 两列均为可空；旧 v0.1 数据行 auth 信息为 NULL 不会破坏既有记录。
-- Phase 1 Task 4 引入 ExecutionAttempt 实体时再写入逻辑字段。
ALTER TABLE kylin_pending_action ADD COLUMN creator_principal      VARCHAR(64);
ALTER TABLE kylin_pending_action ADD COLUMN creator_auth_session_id VARCHAR(64);

-- ---------- kylin_execution_attempt：新表 ----------
-- 一次执行的「开始」原子审计：attempt_id 对外暴露（UUID），audit_id 串到 V1 审计。
CREATE TABLE kylin_execution_attempt (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id      VARCHAR(36)  NOT NULL UNIQUE,
    audit_id        VARCHAR(64)  NOT NULL,
    action_id       VARCHAR(64),
    action_type     VARCHAR(64)  NOT NULL,
    target_summary  VARCHAR(256),
    started_at      TIMESTAMP    NOT NULL,
    created_at      TIMESTAMP    NOT NULL
);

CREATE INDEX idx_attempt_audit_id  ON kylin_execution_attempt(audit_id);
CREATE INDEX idx_attempt_started_at ON kylin_execution_attempt(started_at);

-- ---------- kylin_execution_outcome：新表 ----------
-- 一次执行的「结果」原子审计：outcome 与 attempt 1:1，attempt_id 唯一。
-- evidence_json 存执行证据（命令、时间戳、退出码），不存 LLM 链式思考。
CREATE TABLE kylin_execution_outcome (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outcome_id      VARCHAR(36)  NOT NULL UNIQUE,
    attempt_id      VARCHAR(36)  NOT NULL UNIQUE,
    status          VARCHAR(16)  NOT NULL,
    summary         TEXT,
    evidence_json   TEXT,
    finished_at     TIMESTAMP    NOT NULL,
    created_at      TIMESTAMP    NOT NULL
);

CREATE INDEX idx_outcome_attempt_id ON kylin_execution_outcome(attempt_id);
