-- ============================================================
-- V3: LLM 调用审计 (Phase 3 Task 5)
-- ============================================================
-- 目标：在 V1/V2 之上增量引入「LLM 调用摘要审计」所需的新表 kylin_llm_call_record。
-- 严格遵守 CLAUDE.md / phase3-llm-integration-plan §Task 5：
--   * 仅增量：不删列、不改名、不破坏 V1/V2 数据
--   * 不引用 V1/V2 旧表的外键（V3 是独立审计表，audit_id 仅作关联字段）
--   * SQL 子集：bigint generated by default as identity / varchar / timestamp
--     与 V1/V2 完全一致（保持 H2 PostgreSQL 模式 + 真实 PostgreSQL 12+ 双向兼容）
--
-- 安全红线（来自 P3-T5 契约）：
--   * 绝不存储：apiKey / prompt / responseContent / reasoning / raw tool output
--   * 仅记录 bounded summary：auditId / stage / model / durationMs / status / reason / token 计数 / createdAt
--   * reason 仅记 LlmClientException.Reason 枚举名（不记 message 原文 — 防敏感泄漏）
-- ============================================================

CREATE TABLE kylin_llm_call_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id          VARCHAR(64)  NOT NULL,
    stage             VARCHAR(16)  NOT NULL,
    model             VARCHAR(64)  NOT NULL,
    duration_ms       BIGINT       NOT NULL,
    status            VARCHAR(16)  NOT NULL,
    reason            VARCHAR(64),
    prompt_tokens     INT,
    completion_tokens INT,
    total_tokens      INT,
    created_at        TIMESTAMP    NOT NULL
);

CREATE INDEX idx_llm_call_audit_id   ON kylin_llm_call_record(audit_id);
CREATE INDEX idx_llm_call_created_at ON kylin_llm_call_record(created_at);