-- ============================================================
-- V5: Notification Center (Phase 1 / P1-01 Plan 01 Task 2)
-- ============================================================
-- 目标：在 V1-V4 基线之上增量引入通知中心的持久化表 notification_records。
-- 严格遵守 CLAUDE.md / phase1-runtime-database-plan：
--   * 仅增量：不删列、不改名、不破坏既有数据
--   * 不引用 V1-V4 旧表的外键（audit_id 仅作关联字段，便于未来归档）
--   * SQL 子集：bigint generated by default as identity / varchar / text / timestamp
--     与 V1-V4 完全一致（保持 H2 PostgreSQL 模式 + 真实 PostgreSQL 12+ 双向兼容）
--
-- 安全红线（来自 P1-01 设计 §4.6）：
--   * requestPayload / responseBody 已是脱敏后 / 截断后的字符串
--   * 联合唯一 (event_id, channel_id) — 防止同一事件对同一通道重复入队
--   * errorMessage 限长 500，dispatcher 在写入时已脱敏
-- ============================================================

CREATE TABLE notification_records (
    record_id        VARCHAR(36)  NOT NULL PRIMARY KEY,
    event_id         VARCHAR(36)  NOT NULL,
    audit_id         VARCHAR(64)  NOT NULL,
    channel_id       VARCHAR(100) NOT NULL,
    channel_type     VARCHAR(20)  NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    request_payload  ${lob_type},
    response_body    ${lob_type},
    response_code    INTEGER,
    error_message    VARCHAR(500),
    retry_count      INTEGER      NOT NULL DEFAULT 0,
    sent_at          TIMESTAMP,
    created_at       TIMESTAMP    NOT NULL,
    CONSTRAINT uk_event_channel UNIQUE (event_id, channel_id)
);

CREATE INDEX idx_audit_id   ON notification_records (audit_id);
CREATE INDEX idx_created_at ON notification_records (created_at);
