-- ============================================================
-- V7: Scheduled Inspection (Phase 1 / P1-02 MVP)
-- ============================================================
-- 目标：在 V6 通知管理之上引入"无人值守定时巡检"所需的 2 张表 + 4 个索引,
--       并在 kylin_audit_log 上增加 trigger_type / operator 两列以便
--       Task 4 把巡检来源写入审计。
--
-- 触发原因(P1-02 设计文档 §5 + Plan 02 Task 2):
--   * inspection_plans 存巡检计划快照,含 next_run_at / version(乐观锁) /
--     template_params_json / thresholds_json / schedule_config_json 等结构化 JSON。
--   * inspection_executions 存单次执行,plan_id 是普通 String 字段(无 FK),
--     即使 plan 被删除,execution / report / audit 历史仍可保留。
--   * 同计划重入通过 InspectionPlanRepository.findByPlanIdForUpdate 的
--     PESSIMISTIC_WRITE 行锁串行化,无需 partial index / JVM 内存锁。
--   * audit_logs 增加 trigger_type(SCHEDULED/MANUAL) 与 operator
--     (SYSTEM_SCHEDULER/<admin>) 两 nullable 列,旧 v0.1 行不写也无破坏。
--
-- 严格遵守 CLAUDE.md / phase1-runtime-database-plan:
--   * 仅增量:不删列、不改名、不破坏既有数据
--   * SQL 子集:bigint / varchar / text / timestamp / boolean 与 V1-V6 完全一致
--     (保持 H2 PostgreSQL 模式 + 真实 PostgreSQL 双向兼容)
--   * ${lob_type} 占位符延续 V1/V2/V4/V5 用法:H2=CLOB, PG=TEXT
--   * 不使用 H2-only generated columns 或 PostgreSQL-only partial index
--     (idx_inspection_plan_due 不写 WHERE 过滤,改为普通索引,enabled=true
--      的额外过滤在 Service 层完成)
--   * 不建立 inspection_executions.plan_id → inspection_plans 的外键
--     (设计要求 plan_id 是普通 String 字段,删除计划不级联)
--
-- 安全红线(P1-02 设计 §4 + §5.4):
--   * 巡检执行不调用任何写工具、不创建 PendingAction
--   * 审计 trigger_type / operator 两列仅为识别巡检来源,不影响安全决策
-- ============================================================

-- ---------- kylin_audit_log：增加巡检来源两列(都为 nullable) ----------
-- trigger_type: SCHEDULED / MANUAL
-- operator: SYSTEM_SCHEDULER / <admin username>
ALTER TABLE kylin_audit_log ADD COLUMN trigger_type VARCHAR(32);
ALTER TABLE kylin_audit_log ADD COLUMN operator    VARCHAR(128);

-- ---------- inspection_plans：巡检计划持久化 ----------
CREATE TABLE inspection_plans (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id               VARCHAR(36)  NOT NULL UNIQUE,
    name                  VARCHAR(128) NOT NULL,
    description           VARCHAR(512),
    template_type         VARCHAR(16)  NOT NULL,
    template_params_json  ${lob_type},
    thresholds_json       ${lob_type},
    schedule_type         VARCHAR(16)  NOT NULL,
    schedule_config_json  ${lob_type}  NOT NULL,
    timezone              VARCHAR(64)  NOT NULL,
    notification_policy   VARCHAR(16)  NOT NULL,
    enabled               BOOLEAN      NOT NULL DEFAULT FALSE,
    next_run_at           TIMESTAMP,
    last_run_at           TIMESTAMP,
    version               BIGINT       NOT NULL DEFAULT 0,
    created_at            TIMESTAMP    NOT NULL,
    updated_at            TIMESTAMP    NOT NULL
);

-- 按 plan.name 唯一(管理员侧"按名称去重")— 命名为 uk_inspection_plan_name
-- (注意:此处 uk_ 是"unique key"前缀,与表名组合成业务唯一键的常规命名)
CREATE UNIQUE INDEX uk_inspection_plan_name ON inspection_plans (name);

-- 调度器拉取到期计划用(next_run_at)。普通索引,enabled=true 的过滤在 Service 层
-- 完成 — 不写 WHERE 过滤以避开 PostgreSQL-only partial index。
CREATE INDEX idx_inspection_plan_due ON inspection_plans (next_run_at);

-- ---------- inspection_executions：巡检执行记录 ----------
-- plan_id 是普通 String 字段(无 @ManyToOne / 无 FOREIGN KEY);
-- 删除计划时执行历史保留。
CREATE TABLE inspection_executions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id           VARCHAR(36)  NOT NULL UNIQUE,
    plan_id                VARCHAR(36)  NOT NULL,
    plan_snapshot_json     ${lob_type},
    status                 VARCHAR(20)  NOT NULL,
    trigger_type           VARCHAR(32)  NOT NULL,
    operator               VARCHAR(128) NOT NULL,
    started_at             TIMESTAMP    NOT NULL,
    finished_at            TIMESTAMP,
    summary                VARCHAR(1024),
    audit_id               VARCHAR(36),
    report_id              VARCHAR(36),
    abnormal               BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMP    NOT NULL,
    updated_at             TIMESTAMP    NOT NULL
);

-- 按 plan_id + started_at DESC 拉取某计划的最近执行历史
CREATE INDEX idx_inspection_execution_plan_started
    ON inspection_executions (plan_id, started_at DESC);

-- 启动期恢复查询用: WHERE status = 'RUNNING' AND started_at < threshold
CREATE INDEX idx_inspection_execution_status
    ON inspection_executions (status);
